export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_ERROR_FIRST = "GET_ERROR_FIRST";
export const GET_ERROR_SECOND = "GET_ERROR_SECOND";
export const GET_DELETE_RESPONSE = "GET_DELETE_RESPONSE";
export const GET_UPDATE_RESPONSE = "GET_UPDATE_RESPONSE";
