GET http://localhost:5000/api/customers

###

GET http://localhost:5000/api/customers/62a21b17456c31c6fb473831

###

POST http://localhost:5000/api/customers
Content-Type: application/json

{
    "firstName": "Bruce",
    "lastName": "Lee"
}

###

DELETE http://localhost:5000/api/customers/62a21e8a0b27a9f47289b586

###

PUT http://localhost:5000/api/customers/62a21e8a0b27a9f47289b586
Content-Type: application/json

{
    "firstName": "Chuck",
    "lastName": "Norris"
}